name: CustomFish
version: 1.0
main: online.aeck.customfish.CustomFish
api-version: '1.21'
author: AECK
softdepend: [Vault, PlaceholderAPI]

commands:
  banca:
    description: Menu ban ca AECK.ONLINE
  muacauca:
    description: Dieu chinh mua thoi tiet
    permission: aeck.admin
  topcauca:
    description: Xem bang xep hang cau ca
  fish:
    description: Lenh quan tri plugin (Reload)
    permission: aeck.admin
  fishinventory:
    description: GUI lay tat ca vat pham plugin (Admin)
    permission: aeck.admin
  nangcapcan:
    description: Nang cap linh kien can cau
  kinhnghiemcauca:
    description: Xem kinh nghiem cau ca va diem ky nang
  kynangcauca:
    description: Mo cay ky nang cau ca
  nhiemvucauca:
    description: Nhan nhiem vu cau ca
  nvcauca:
    description: Nhan nhiem vu cau ca (viet tat)
